DROP TABLE IF EXISTS app_lfg;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(250) NOT NULL,
	mail VARCHAR(250) NOT NULL,
	name VARCHAT(30) NOT NULL,
	last_name VARHCAR(250) NOT NULL,
	steam VARCHAT(30),
	creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE videogames (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	platform VARCHAR(250) NOT NULL,
	developer VARCHAR(100) NOT NULL,
	gender VARCHAR(250) NOT NULL
);

CREATE TABLE parties (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	creator INT NOT NULL,
	description VARCHAR(250),
	creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	game INT NOT NULL,
	FOREIGN KEY (creator) REFERENCES users(id),
	POREIGN KEY (game) REFERENCES videogames(id)
);

CREATE TABLE members (
	user INT NOT NULL,
	party INT NOT NULL,
	union_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user, party),
	FOREIGN KEY (user) REFERENCES users(id),
	FOREIGN KEY (party) REFERENCES parties(id)
);

CREATE TABLE messages (
	id INT AUTO_INCREMENT PRIMARY KEY,
	content VARCHAR(250) NOT NULL,
	creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	user INT NOT NULL,
	party INT NOT NULL,
	FOREIGN KEY (user) REFERENCES users(id),
	FOREIGN KEY (party) REFERENCES parties(id)
);

